### ISSUE TITLE
Plume install is broken

### ISSUE THREAD

**Issue by panzertime** [redcanari/canari3#30]
I cannot install Plume.  When I attempt to do `canari install-plume`, the installer takes me through almost all of the steps before saying 

```
Traceback (most recent call last):
  File "/usr/local/bin/canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==3.1.3', 'canari')
  File "/home/rt/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 765, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/rt/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1545, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.1.3-py2.7.egg/EGG-INFO/scripts/canari", line 22, in <module>
    canari_main()
  File "/usr/local/lib/python2.7/dist-packages/canari-3.1.3-py2.7.egg/canari/commands/framework.py", line 33, in _func
    return func(self.parser.parse_args(args_, namespace))
  File "/usr/local/lib/python2.7/dist-packages/canari-3.1.3-py2.7.egg/canari/commands/common.py", line 61, in canari_main
    opts.command_function(opts)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.1.3-py2.7.egg/canari/commands/install_plume.py", line 126, in install_plume
    return install_wizard(opts)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.1.3-py2.7.egg/canari/commands/install_plume.py", line 170, in install_wizard
    configurator.render()
  File "/home/rt/.local/lib/python2.7/site-packages/mrbob/configurator.py", line 192, in render
    self.ignored_directories)
  File "/home/rt/.local/lib/python2.7/site-packages/mrbob/rendering.py", line 82, in render_structure
    renderer,
  File "/home/rt/.local/lib/python2.7/site-packages/mrbob/rendering.py", line 102, in render_template
    output = renderer(source_output, variables)
  File "/home/rt/.local/lib/python2.7/site-packages/mrbob/rendering.py", line 22, in <lambda>
    jinja2_renderer = lambda s, v: jinja2_env.from_string(s).render(parse_variables(v))
  File "/home/rt/.local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/rt/.local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 28, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'venv'
```

**Comment by panzertime** [comment]
(This is compounded by the fact that documentation for both Canari 3 and Canari 2 is available online.  Something should be done to fix that.)

**Comment by allfro** [comment]
Hi there,

Let me take a look. Are you using a virtual environment for your canari install?

**Comment by panzertime** [comment]
I don't remember.  I stopped working on this when install-plume didn't work, and I haven't come back to it since then.

**Comment by panzertime** [comment]
I'll close this issue, and if I come back to this and it's still broken, I'll open a new one with more details.

**Comment by allfro** [comment]
Should be fixed in this PR https://github.com/redcanari/canari3/pull/26
