### ISSUE TITLE
Required libraries are not available on Windows platform

### ISSUE THREAD

**Issue by norman-ingal** [redcanari/canari3#31]
Hi,

I tried installing Canari from source and also using the easy_install command. Installation was successful but canari can't run. 

Below is the error message:
```
c:\Maltego\canari3-master>canari list-commands
Traceback (most recent call last):
  File "C:\Python27\Scripts\\canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==3.2.0', 'canari')
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "c:\python27\lib\site-packages\canari-3.2.0-py2.7.egg\EGG-INFO\scripts\canari", line 7, in <module>
    from canari.commands.common import canari_main
  File "C:\Python27\lib\site-packages\canari-3.2.0-py2.7.egg\canari\commands\common.py", line 4, in <module>
    import pwd
ImportError: No module named pwd
```

**Comment by norman-ingal** [comment]
I tried to comment some unsupported code to force it to run and here are additional python built-in functions that are not available on Windows:
readline
grp
pwd


```
c:\Maltego\canari3-master>canari list-commands
Traceback (most recent call last):
  File "C:\Python27\Scripts\\canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==3.2.0', 'canari')
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "c:\python27\lib\site-packages\canari-3.2.0-py2.7.egg\EGG-INFO\scripts\canari", line 7, in <module>
    from canari.commands.common import canari_main
  File "C:\Python27\lib\site-packages\canari-3.2.0-py2.7.egg\canari\commands\common.py", line 4, in <module>
    import pwd
ImportError: No module named pwd
```

```
c:\Maltego\canari3-master>canari list-commands
Traceback (most recent call last):
  File "C:\Python27\Scripts\\canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==3.2.0', 'canari')
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "c:\python27\lib\site-packages\canari-3.2.0-py2.7.egg\EGG-INFO\scripts\canari", line 10, in <module>
    from canari.commands import *
  File "C:\Python27\lib\site-packages\canari-3.2.0-py2.7.egg\canari\commands\create_package.py", line 8, in <module>
    from mrbob.configurator import Configurator
  File "C:\Python27\lib\site-packages\mrbob\configurator.py", line 6, in <module>
    import readline
ImportError: No module named readline
```

```
c:\Maltego\canari3-master>canari list-commands
Traceback (most recent call last):
  File "C:\Python27\Scripts\\canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==3.2.0', 'canari')
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "c:\python27\lib\site-packages\canari-3.2.0-py2.7.egg\EGG-INFO\scripts\canari", line 10, in <module>
    from canari.commands import *
  File "C:\Python27\lib\site-packages\canari-3.2.0-py2.7.egg\canari\commands\install_plume.py", line 3, in <module>
    import grp
ImportError: No module named grp
```

**Comment by allfro** [comment]
Great!  I'll get those ported. Are you running py3 or py2?
