### ISSUE TITLE
_tkinter module not found error 

### ISSUE THREAD

**Issue by captainhowdy1** [redcanari/canari3#38]
I am running into this error when I run create-profile from inside the src folder of a maltego package. 
`Traceback (most recent call last):
  File "/usr/local/bin/canari", line 3, in <module>
    from canari.entrypoints import main
  File "/home/c4pta1n/.local/lib/python3.6/site-packages/canari/entrypoints.py", line 21, in <module>
    from canari.easygui import passwordbox
  File "/home/c4pta1n/.local/lib/python3.6/site-packages/canari/easygui.py", line 147, in <module>
    from tkinter import *
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

This began about a week ago and after researching it a bit I reinstalled tk and tk-dev along with tcl and tcllib.  I recompiled python2.7.15 and have given it another go. I am still receiving the same error when running; create-profile, create-package, debug-transform, or  create- install. I have not had any working canari commands that I have tried execute without this error occurring. 
I am able to import _Tkinter from a python shell but not tkinter and I can run any tk commands that I have tried without issue

Any help to resolve this would be much appreciated.

**Comment by captainhowdy1** [comment]
I recompiled and ensure that tk support was added. I now recieve this error when I attempt to run any command with using any version of pip `Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==10.0.1', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-39.2.0-py2.7.egg/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-39.2.0-py2.7.egg/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-39.2.0-py2.7.egg/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-39.2.0-py2.7.egg/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/index.py", line 15, in <module>
    from pip._vendor import html5lib, requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 86, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/certificate_transparency.py", line 22, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: 'module' object has no attribute 'add_metaclass'
`
And when I attempt to use canari I have gotten this error on the create-profile command, `Traceback (most recent call last):
  File "/usr/local/bin/canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==3.2.2', 'canari')
  File "/usr/local/lib/python2.7/dist-packages/setuptools-39.2.0-py2.7.egg/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-39.2.0-py2.7.egg/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.2.2-py2.7.egg/EGG-INFO/scripts/canari", line 16, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/canari-3.2.2-py2.7.egg/canari/entrypoints.py", line 44, in main
    canari_main()
  File "/usr/local/lib/python2.7/dist-packages/canari-3.2.2-py2.7.egg/canari/commands/framework.py", line 33, in _func
    return func(self.parser.parse_args(args_, namespace))
  File "/usr/local/lib/python2.7/dist-packages/canari-3.2.2-py2.7.egg/canari/commands/common.py", line 67, in canari_main
    opts.command_function(opts)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.2.2-py2.7.egg/canari/commands/create_profile.py", line 59, in create_profile
    transform_package = TransformDistribution(opts.package)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.2.2-py2.7.egg/canari/pkgutils/transform.py", line 73, in __init__
    (self.name, self.name, e))
ImportError: Does not appear to be a valid canari package. Couldn't import the 'rapleaf.transforms' package in 'rapleaf'. `

**Comment by allfro** [comment]
This has nothing to do with Canari at this point. It seems like your
setuptools are broken. I would install  the official binaries of py
instead.
