### ISSUE TITLE
Missing UTF-8 support?

### ISSUE THREAD

**Issue by xehartnort** [redcanari/canari3#49]
Hello,

I've been developing a new maltego transform which sends some utf-8 strings, but I am unable to run it successfully because it looks like  canari doesn't have utf-8 support. This is the error:

```
 `- MaltegoTransformExceptionMessage:  
  `- Exceptions:  
    `- Exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/canari-3.3.8-py2.7.egg/canari/maltego/runner.py", line 135, in local_transform_runner
    message_writer(msg)
  File "/usr/lib/python2.7/site-packages/canari-3.3.8-py2.7.egg/canari/maltego/runner.py", line 219, in console_writer
    msg = fromstring(msg.render())
  File "<string>", line 124, in XML
UnicodeEncodeError: 'ascii' codec can't encode character u'\u030a' in position 274319: ordinal not in range(128)
```

I am using the docker image 3.3.8-alpine with plume installed, this is my dockerfile:

```
FROM redcanari/canari:3.3.8-alpine

ADD . /root/sdist

RUN apk add --no-cache \
        alpine-sdk \
        python-dev \
        openssl-dev \
        py-cffi \
        python2-tkinter && \
    cd /root/sdist && \
    pip install pyopenssl service_identity requests && \
    python setup.py install && \
    yes | canari create-profile XXX && \
    cd /root && \
    mkdir -p /var/plume && \
    cd /var/plume && \
    canari install-plume -y && \
    canari load-plume-package -y XXX && \
    apk del \
        alpine-sdk \
        python-dev

EXPOSE 8080

ENTRYPOINT /etc/init.d/plume start-docker
```

**Comment by xehartnort** [comment]
Hello, I've solved it, It is a bug in ElementTree.fromstring: [https://bugs.python.org/issue11033](https://bugs.python.org/issue11033) 

In order to fix it, In the file  **/usr/lib/python2.7/site-packages/canari-3.3.8-py2.7.egg/canari/maltego/runner.py** I've replaced line 220: 

`
msg = fromstring(msg.render())
`

with this one:

`msg = fromstring(msg.render().encode('utf-8'))`


I'm going to make a pull request with this changes even thought it looks like python2 version is not in development anymore.
